# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fa0bffb98cb4f413f5f092a0f2f6c5c"
<<<<<<< HEAD
application_url = "https://hit-sydney-kinase-grow.trycloudflare.com"
=======
application_url = "https://gang-symantec-exceed-photographs.trycloudflare.com"
>>>>>>> b692de7 (pubsub and scopes update)
embedded = true
name = "test-dm-app"
handle = "test-dm-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "pubsub://{projectid}:{topic_id}"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "pubsub://{projectid}:{topic_id}"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "pubsub://{projectid}:{topic_id}"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://gang-symantec-exceed-photographs.trycloudflare.com/auth/callback",
  "https://gang-symantec-exceed-photographs.trycloudflare.com/auth/shopify/callback",
  "https://gang-symantec-exceed-photographs.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "testdm-app-dev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
